export const AVATAR_URL = 'https://rickandmortyapi.com/api/character/avatar/';

export const COLORS = {
  icon: 'black',
  shadow: 'black',
  textShadow: 'white',
  placeceholder: 'black',
  searchText: 'black',
  text: 'white',
  dead: 'red',
  alive: 'green',
  unknown: 'black',
  background: 'lightgrey',
  tabBarInactiveBackground: '#8067ed',
  tabBarBackground: '#7b5dff',
};

export const FONTS = {
  general: 'Dosis-Regular',
  stamp: 'OldStamper',
};

export const CHARACTERS = [
  {id: '802', name: '26 Years Old Morty'},
  {id: '803', name: '40 Years Old Morty'},
  {id: '801', name: '7+7 Years Old Morty'},
  {id: '583', name: "80's snake"},
  {id: '6', name: 'Abadango Cluster Princess'},
  {id: '7', name: 'Abradolf Lincler'},
  {id: '597', name: 'Abradolf Lincler'},
  {id: '398', name: 'Accountant dog'},
  {id: '680', name: 'Adam'},
  {id: '681', name: "Adam's Mother"},
  {id: '8', name: 'Adjudicator Rick'},
  {id: '9', name: 'Agency Director'},
  {id: '722', name: 'Air Tina-Teer'},
  {id: '10', name: 'Alan Rails'},
  {id: '11', name: 'Albert Einstein'},
  {id: '12', name: 'Alexander'},
  {id: '792', name: 'Alien Crow'},
  {id: '793', name: 'Alien Crow'},
  {id: '13', name: 'Alien Googah'},
  {id: '411', name: 'Alien Mexican Armada'},
  {id: '14', name: 'Alien Morty'},
  {id: '15', name: 'Alien Rick'},
  {id: '470', name: 'Alien Spa Employee'},
  {id: '743', name: 'Alyson Hannigan'},
  {id: '734', name: 'Amazing Johnathan'},
  {id: '16', name: 'Amish Cyborg'},
  {id: '247', name: 'Amy Poopybutthole'},
  {id: '447', name: 'Anchor Gear'},
  {id: '510', name: 'Anchorman'},
  {id: '511', name: 'Anchorwoman'},
  {id: '581', name: 'Anchosnake'},
  {id: '582', name: 'Anchosnake'},
  {id: '804', name: 'Andy'},
  {id: '546', name: 'Angie Flint'},
  {id: '640', name: 'Angry Glorzo'},
  {id: '17', name: 'Annie'},
  {id: '18', name: 'Antenna Morty'},
  {id: '19', name: 'Antenna Rick'},
  {id: '20', name: 'Ants in my Eyes Johnson'},
  {id: '21', name: 'Aqua Morty'},
  {id: '22', name: 'Aqua Rick'},
  {id: '454', name: 'Arbolian Mentirososian'},
  {id: '23', name: 'Arcade Alien'},
  {id: '24', name: 'Armagheadon'},
  {id: '25', name: 'Armothy'},
  {id: '26', name: 'Arthricia'},
  {id: '27', name: 'Artist Morty'},
  {id: '28', name: 'Attila Starwar'},
  {id: '29', name: 'Baby Legs'},
  {id: '417', name: 'Baby Legs Chief'},
  {id: '805', name: 'Baby Mouse Skin Morty'},
  {id: '30', name: 'Baby Poopybutthole'},
  {id: '472', name: 'Baby Rick'},
  {id: '31', name: 'Baby Wizard'},
  {id: '814', name: 'Bald Rick'},
  {id: '562', name: 'Balthromaw'},
  {id: '584', name: 'Bar Customer'},
  {id: '585', name: 'Bartender'},
  {id: '473', name: 'Bartender Morty'},
  {id: '441', name: 'Bearded Jerry'},
  {id: '32', name: 'Bearded Lady'},
  {id: '392', name: 'Bearded Morty'},
  {id: '33', name: 'Beebo'},
  {id: '34', name: 'Benjamin'},
  {id: '35', name: 'Bepisian'},
  {id: '36', name: 'Beta-Seven'},
  {id: '37', name: 'Beth Sanchez'},
  {id: '807', name: 'Beth Sanchez'},
  {id: '4', name: 'Beth Smith'},
  {id: '38', name: 'Beth Smith'},
  {id: '39', name: 'Beth Smith'},
  {id: '628', name: 'Beth Smith'},
  {id: '40', name: "Beth's Mytholog"},
  {id: '598', name: 'Biblesaurus'},
  {id: '41', name: 'Big Boobed Waitress'},
  {id: '769', name: 'Big Fat rick'},
  {id: '42', name: 'Big Head Morty'},
  {id: '43', name: 'Big Morty'},
  {id: '45', name: 'Bill'},
  {id: '46', name: 'Bill'},
  {id: '47', name: 'Birdperson'},
  {id: '599', name: 'Birdperson'},
  {id: '786', name: "Birdperson & Tammy's Child"},
  {id: '48', name: 'Black Rick'},
  {id: '49', name: 'Blamph'},
  {id: '732', name: 'Blazen'},
  {id: '50', name: 'Blim Blam'},
  {id: '51', name: 'Blue Diplomat'},
  {id: '52', name: 'Blue Footprint Guy'},
  {id: '53', name: 'Blue Shirt Morty'},
  {id: '54', name: 'Bobby Moynihan'},
  {id: '44', name: 'Body Guard Morty'},
  {id: '523', name: 'Boglin'},
  {id: '55', name: 'Boobloosian'},
  {id: '56', name: 'Bootleg Portal Chemist Rick'},
  {id: '57', name: 'Borpocian'},
  {id: '674', name: 'Bova'},
  {id: '58', name: 'Brad'},
  {id: '59', name: 'Brad Anderson'},
  {id: '641', name: 'Bruce'},
  {id: '742', name: 'Bruce Chutback'},
  {id: '100', name: 'Bubonic Plague'},
  {id: '509', name: 'Bully'},
  {id: '826', name: 'Butter Robot'},
  {id: '459', name: 'Butthole Ice Cream Guy'},
  {id: '60', name: 'Calypso'},
  {id: '61', name: 'Campaign Manager Morty'},
  {id: '62', name: 'Canklanker Thom'},
  {id: '515', name: 'Caterpillar Mr. Goldenfold'},
  {id: '522', name: 'Caterpillar Mr. Goldenfold’s Larvae'},
  {id: '600', name: 'Cats Fan'},
  {id: '587', name: 'Cavesnake'},
  {id: '176', name: 'Celebrity Jerry'},
  {id: '744', name: 'Cenobite'},
  {id: '745', name: 'Cenobite'},
  {id: '746', name: 'Cenobite'},
  {id: '747', name: 'Cenobite'},
  {id: '748', name: 'Cenobite'},
  {id: '63', name: 'Centaur'},
  {id: '570', name: 'Chachi'},
  {id: '431', name: 'Chair-homeless'},
  {id: '429', name: 'Chair-person'},
  {id: '430', name: 'Chair-person'},
  {id: '432', name: 'Chair-waiter'},
  {id: '490', name: 'Chang'},
  {id: '751', name: 'Changeformer'},
  {id: '752', name: 'Changeformer'},
  {id: '64', name: 'Chris'},
  {id: '65', name: 'Chris'},
  {id: '601', name: 'Christmas Storyteller'},
  {id: '729', name: 'CHUD King'},
  {id: '737', name: 'Cirque du Soleil Zumanity Member'},
  {id: '738', name: 'Cirque du Soleil Zumanity Member'},
  {id: '739', name: 'Cirque du Soleil Zumanity Member'},
  {id: '740', name: 'Cirque du Soleil Zumanity Member'},
  {id: '741', name: 'Cirque du Soleil Zumanity Member'},
  {id: '66', name: 'Coach Feratu (Balik Alistane)'},
  {id: '749', name: 'Coat Rack Head'},
  {id: '67', name: 'Collector'},
  {id: '488', name: 'Colonial Rick'},
  {id: '68', name: 'Colossus'},
  {id: '69', name: 'Commander Rick'},
  {id: '461', name: "Communication's Responsible Rick"},
  {id: '70', name: 'Concerto'},
  {id: '71', name: 'Conroy'},
  {id: '602', name: 'Cookies Guy'},
  {id: '72', name: 'Cool Rick'},
  {id: '754', name: 'Coop'},
  {id: '73', name: 'Cop Morty'},
  {id: '74', name: 'Cop Rick'},
  {id: '403', name: 'Corn detective'},
  {id: '150', name: 'Cornvelious Daniel'},
  {id: '642', name: 'Council of Glorzos Member'},
  {id: '643', name: 'Council of Glorzos Member'},
  {id: '75', name: 'Courier Flap'},
  {id: '76', name: 'Cousin Nicky'},
  {id: '77', name: 'Cowboy Morty'},
  {id: '78', name: 'Cowboy Rick'},
  {id: '79', name: 'Crab Spider'},
  {id: '80', name: 'Creepy Little Girl'},
  {id: '81', name: 'Crocubot'},
  {id: '83', name: 'Cronenberg Morty'},
  {id: '82', name: 'Cronenberg Rick'},
  {id: '603', name: 'Crossy'},
  {id: '813', name: 'Crow Horse'},
  {id: '808', name: 'Crow Scare'},
  {id: '649', name: 'Crystal Dealer'},
  {id: '650', name: 'Crystal Dealer'},
  {id: '651', name: 'Crystal Dealer'},
  {id: '648', name: 'Crystal Dealers Boss'},
  {id: '494', name: 'Crystal Poacher'},
  {id: '495', name: 'Crystal Poacher'},
  {id: '496', name: 'Crystal Poacher'},
  {id: '84', name: 'Cult Leader Morty'},
  {id: '85', name: 'Cyclops Morty'},
  {id: '86', name: 'Cyclops Rick'},
  {id: '87', name: 'Cynthia'},
  {id: '88', name: 'Cynthia'},
  {id: '89', name: 'Dale'},
  {id: '474', name: 'Dancer Cowboy Morty'},
  {id: '475', name: 'Dancer Morty'},
  {id: '526', name: 'Danny Publitz'},
  {id: '718', name: 'Daphne'},
  {id: '90', name: 'Daron Jefferson'},
  {id: '635', name: 'Darth Poopybutthole'},
  {id: '91', name: 'David Letterman'},
  {id: '92', name: 'Davin'},
  {id: '394', name: 'Davin'},
  {id: '565', name: 'Debrah'},
  {id: '566', name: 'Debrah’s Partner'},
  {id: '667', name: 'Defiance Beth'},
  {id: '669', name: 'Defiance Doctor'},
  {id: '668', name: 'Defiance Squanchette'},
  {id: '812', name: 'Deformed Morty'},
  {id: '530', name: 'Deliverance'},
  {id: '93', name: 'Diablo Verde'},
  {id: '94', name: 'Diane Sanchez'},
  {id: '719', name: 'Diesel Weasel'},
  {id: '95', name: 'Dipper and Mabel Mortys'},
  {id: '102', name: 'Donna Gueterman'},
  {id: '103', name: 'Doofus Rick'},
  {id: '104', name: 'Doom-Nomitron'},
  {id: '433', name: 'Doopidoo'},
  {id: '550', name: 'Double Microwawe'},
  {id: '491', name: 'Dr. Eleanor Arroway'},
  {id: '105', name: 'Dr. Glip-Glop'},
  {id: '106', name: 'Dr. Schmidt'},
  {id: '107', name: 'Dr. Wong'},
  {id: '108', name: 'Dr. Xenon Bloom'},
  {id: '709', name: 'Dracula'},
  {id: '109', name: 'Duck With Muscles'},
  {id: '755', name: 'Dwayne'},
  {id: '101', name: 'E. Coli'},
  {id: '720', name: 'Eddie'},
  {id: '110', name: 'Eli'},
  {id: '111', name: "Eli's Girlfriend"},
  {id: '558', name: 'Elon Tusk'},
  {id: '112', name: 'Eric McMan'},
  {id: '113', name: 'Eric Stoltz Mask Morty'},
  {id: '114', name: 'Ethan'},
  {id: '115', name: 'Ethan'},
  {id: '116', name: 'Evil Beth Clone'},
  {id: '117', name: 'Evil Jerry Clone'},
  {id: '118', name: 'Evil Morty'},
  {id: '636', name: 'Evil Morty'},
  {id: '119', name: 'Evil Rick'},
  {id: '120', name: 'Evil Summer Clone'},
  {id: '683', name: 'Evolved Narnian'},
  {id: '685', name: 'Evolved Narnian Disguised as Morty'},
  {id: '121', name: 'Eyehole Man'},
  {id: '122', name: 'Fart'},
  {id: '499', name: 'Fascist Morty'},
  {id: '500', name: 'Fascist Mr. President'},
  {id: '498', name: 'Fascist Rick'},
  {id: '501', name: 'Fascist Rick’s Clone'},
  {id: '505', name: 'Fascist Shrimp Morty'},
  {id: '503', name: 'Fascist Shrimp Rick'},
  {id: '504', name: 'Fascist Shrimp Rick’s Clone'},
  {id: '506', name: 'Fascist Shrimp SS'},
  {id: '507', name: 'Fascist Teddy Bear Rick'},
  {id: '508', name: 'Fascist Teddy Bear Rick’s Clone'},
  {id: '123', name: 'Fat Morty'},
  {id: '124', name: 'Father Bob'},
  {id: '604', name: 'Female Scorpion'},
  {id: '798', name: 'Ferkusian'},
  {id: '397', name: 'Fido'},
  {id: '125', name: 'Flansian'},
  {id: '126', name: 'Fleeb'},
  {id: '594', name: 'Floaty Bloody Man'},
  {id: '605', name: 'Floaty Bloody Man’s Daughter'},
  {id: '595', name: 'Floaty Non-Gasm Brotherhood Member'},
  {id: '596', name: 'Floaty Non-Gasm Brotherhood Member Friend'},
  {id: '665', name: 'Florflock'},
  {id: '476', name: 'Flower Morty'},
  {id: '735', name: 'Foal Sanchez'},
  {id: '127', name: 'Frank Palicky'},
  {id: '128', name: "Frankenstein's Monster"},
  {id: '756', name: 'Franklin D. Roosevelt'},
  {id: '129', name: 'Fulgora'},
  {id: '457', name: 'Funny Songs Presenter'},
  {id: '662', name: 'Gaia'},
  {id: '130', name: 'Galactic Federation President'},
  {id: '131', name: 'Gar Gloonch'},
  {id: '132', name: "Gar's Mytholog"},
  {id: '133', name: 'Garblovian'},
  {id: '134', name: 'Garmanarnar'},
  {id: '135', name: 'Garment District Rick'},
  {id: '136', name: 'Gazorpazorpfield'},
  {id: '448', name: 'Gear Cop'},
  {id: '137', name: 'Gene'},
  {id: '138', name: 'General Nathan'},
  {id: '139', name: 'General Store Owner'},
  {id: '140', name: 'Genital Washer'},
  {id: '141', name: 'Ghost in a Jar'},
  {id: '758', name: 'Giant Assassin Hidden in the Statue of Liberty'},
  {id: '412', name: 'Giant Cat Monster'},
  {id: '400', name: 'Giant Judge'},
  {id: '436', name: 'Giant Testicle Monster'},
  {id: '142', name: 'Gibble Snake'},
  {id: '547', name: 'Glar'},
  {id: '143', name: 'Glasses Morty'},
  {id: '144', name: 'Glenn'},
  {id: '145', name: 'Glenn'},
  {id: '146', name: 'Glexo Slim Slom'},
  {id: '693', name: 'Glockenspiel Beth'},
  {id: '692', name: 'Glockenspiel Jerry'},
  {id: '696', name: 'Glockenspiel Morty'},
  {id: '694', name: 'Glockenspiel Rick'},
  {id: '695', name: 'Glockenspiel Summer'},
  {id: '525', name: 'Glootie'},
  {id: '147', name: 'Gobo'},
  {id: '148', name: 'Goddess Beth'},
  {id: '97', name: 'Gonorrhea'},
  {id: '606', name: 'Goomby'},
  {id: '149', name: 'Gordon Lunas'},
  {id: '821', name: 'Gotron'},
  {id: '776', name: 'Gotron Pilot'},
  {id: '777', name: 'Gotron Pilot'},
  {id: '778', name: 'Gotron Pilot'},
  {id: '559', name: 'Gramuflackian Anchorman'},
  {id: '560', name: 'Gramuflackian General'},
  {id: '426', name: 'Greasy Grandma'},
  {id: '395', name: 'Greebybobe'},
  {id: '702', name: 'Gun Brain Rick'},
  {id: '402', name: 'Guy from The Bachelor'},
  {id: '151', name: 'Gwendolyn'},
  {id: '477', name: 'Hairdresser Rick'},
  {id: '607', name: 'Hairspray Fan'},
  {id: '152', name: 'Hammerhead Morty'},
  {id: '153', name: 'Hamster In Butt'},
  {id: '154', name: 'Hamurai'},
  {id: '155', name: 'Harold'},
  {id: '790', name: 'Harold (Garbage Goober)'},
  {id: '791', name: "Harold's Wife"},
  {id: '545', name: 'Heist-Con Receptionist'},
  {id: '554', name: 'Heistotron'},
  {id: '156', name: 'Hemorrhage'},
  {id: '98', name: 'Hepatitis A'},
  {id: '99', name: 'Hepatitis C'},
  {id: '556', name: 'Hephaestus'},
  {id: '655', name: 'Heroine Keith'},
  {id: '590', name: 'High Pilot'},
  {id: '591', name: 'High Pilot'},
  {id: '157', name: 'Hole in the Wall Where the Men Can See it All'},
  {id: '497', name: 'Hologram Rick'},
  {id: '158', name: 'Hookah Alien'},
  {id: '673', name: 'Hoovy'},
  {id: '770', name: 'Hothead Rick'},
  {id: '159', name: 'Hunter'},
  {id: '160', name: "Hunter's Father"},
  {id: '161', name: 'Hydrogen-F'},
  {id: '162', name: 'Ice-T'},
  {id: '163', name: 'Ideal Jerry'},
  {id: '656', name: 'Impervious to Acid SWAT Officer'},
  {id: '164', name: 'Insurance Rick'},
  {id: '165', name: 'Investigator Rick'},
  {id: '166', name: 'Invisi-trooper'},
  {id: '167', name: 'Izzy'},
  {id: '764', name: 'Jackey'},
  {id: '168', name: 'Jackie'},
  {id: '169', name: 'Jacob'},
  {id: '170', name: 'Jacqueline'},
  {id: '171', name: 'Jaguar'},
  {id: '172', name: 'Jamey'},
  {id: '173', name: 'Jan-Michael Vincent'},
  {id: '675', name: 'Japheth'},
  {id: '677', name: "Japheth's Eldest Son"},
  {id: '679', name: "Japheth's Grandson"},
  {id: '676', name: "Japheth's Middle Son"},
  {id: '678', name: "Japheth's Youngest Son"},
  {id: '535', name: 'Jeff'},
  {id: '174', name: 'Jerry 5-126'},
  {id: '5', name: 'Jerry Smith'},
  {id: '175', name: 'Jerry Smith'},
  {id: '177', name: 'Jerry Smith'},
  {id: '178', name: "Jerry's Mytholog"},
  {id: '445', name: 'Jerryboree Keeper'},
  {id: '446', name: 'Jerryboree Receptionist'},
  {id: '179', name: 'Jessica'},
  {id: '180', name: 'Jessica'},
  {id: '181', name: "Jessica's Friend"},
  {id: '608', name: 'Jesus Christ'},
  {id: '182', name: 'Jim'},
  {id: '657', name: 'Johnny Carson'},
  {id: '183', name: 'Johnny Depp'},
  {id: '184', name: 'Jon'},
  {id: '185', name: 'Joseph Eli Lipkip'},
  {id: '609', name: 'Josh'},
  {id: '610', name: "Josh's Sister"},
  {id: '536', name: 'Josiah'},
  {id: '478', name: 'Journalist Rick'},
  {id: '186', name: 'Joyce Smith'},
  {id: '513', name: 'Judge'},
  {id: '187', name: 'Juggling Rick'},
  {id: '188', name: 'Karen Entity'},
  {id: '189', name: 'Katarina'},
  {id: '733', name: 'Kathy Ireland'},
  {id: '190', name: 'Keara'},
  {id: '191', name: 'Kevin'},
  {id: '552', name: 'Key Catcher'},
  {id: '192', name: 'King Flippy Nips'},
  {id: '193', name: 'King Jellybean'},
  {id: '524', name: 'Kirkland Brand Mr. Meeseeks'},
  {id: '194', name: 'Kozbian'},
  {id: '195', name: 'Kristen Stewart'},
  {id: '196', name: 'Krombopulos Michael'},
  {id: '197', name: 'Kyle'},
  {id: '198', name: 'Lady Katana'},
  {id: '199', name: 'Larva Alien'},
  {id: '200', name: 'Lawyer Morty'},
  {id: '611', name: 'Leah'},
  {id: '201', name: 'Leonard Smith'},
  {id: '202', name: 'Lighthouse Keeper'},
  {id: '203', name: 'Lil B'},
  {id: '204', name: 'Lisa'},
  {id: '205', name: 'Little Dipper'},
  {id: '471', name: 'Little Voltron'},
  {id: '529', name: 'Lizard'},
  {id: '206', name: 'Lizard Morty'},
  {id: '207', name: 'Loggins'},
  {id: '208', name: 'Logic'},
  {id: '818', name: 'Long Hair Rick'},
  {id: '209', name: 'Long Sleeved Morty'},
  {id: '210', name: 'Lucy'},
  {id: '211', name: 'Ma-Sha'},
  {id: '537', name: 'Maggie'},
  {id: '212', name: 'Magma-Q'},
  {id: '213', name: 'Magnesium-J'},
  {id: '214', name: 'Man Painted Silver Who Makes Robot Noises'},
  {id: '612', name: 'Marcus'},
  {id: '762', name: 'Martínez'},
  {id: '763', name: 'Marvin'},
  {id: '768', name: 'Mary-Lou'},
  {id: '215', name: 'Maximums Rickimus'},
  {id: '216', name: 'MC Haps'},
  {id: '217', name: 'Mechanical Morty'},
  {id: '218', name: 'Mechanical Rick'},
  {id: '219', name: 'Mechanical Summer'},
  {id: '220', name: 'Mega Fruit Farmer Rick'},
  {id: '221', name: 'Melissa'},
  {id: '785', name: 'Memory Geardude'},
  {id: '783', name: 'Memory Rick'},
  {id: '784', name: 'Memory Rick'},
  {id: '782', name: 'Memory Squanchy'},
  {id: '780', name: 'Memory Tammy'},
  {id: '701', name: 'Metal Rick'},
  {id: '806', name: 'Metaphor for Capitalism'},
  {id: '437', name: 'Michael'},
  {id: '567', name: 'Michael'},
  {id: '222', name: 'Michael Denny and the Denny Singers'},
  {id: '404', name: 'Michael Jackson'},
  {id: '223', name: 'Michael Jenkins'},
  {id: '224', name: 'Michael McLick'},
  {id: '225', name: 'Michael Thompson'},
  {id: '438', name: "Michael's Lawyer"},
  {id: '613', name: 'Mike Johnson'},
  {id: '544', name: 'Miles Knightly'},
  {id: '226', name: 'Million Ants'},
  {id: '227', name: 'Mitch'},
  {id: '485', name: 'Modern Rick'},
  {id: '228', name: 'Mohawk Guy'},
  {id: '551', name: 'Monitor Lord'},
  {id: '528', name: 'Monogatron Leader'},
  {id: '533', name: 'Monogatron Queen'},
  {id: '799', name: 'Morglutzian'},
  {id: '467', name: 'Morphizer-XE Customer Support'},
  {id: '468', name: 'Morphizer-XE Customer Support'},
  {id: '469', name: 'Morphizer-XE Customer Support'},
  {id: '230', name: 'Morty Jr.'},
  {id: '401', name: "Morty Jr's interviewer"},
  {id: '233', name: 'Morty K-22'},
  {id: '229', name: 'Morty Mart Manager Morty'},
  {id: '231', name: 'Morty Rick'},
  {id: '2', name: 'Morty Smith'},
  {id: '232', name: 'Morty Smith'},
  {id: '234', name: 'Morty Smith'},
  {id: '630', name: 'Morty Smith'},
  {id: '637', name: 'Morty’s Disguise'},
  {id: '659', name: 'Morty’s Father-in-law'},
  {id: '661', name: 'Morty’s Girlfriend'},
  {id: '512', name: 'Morty’s Lawyer'},
  {id: '660', name: 'Morty’s Mother-in-law'},
  {id: '235', name: 'Mortytown Loco'},
  {id: '527', name: 'Mothership Intern'},
  {id: '542', name: 'Mountain Sweat Jerry'},
  {id: '750', name: 'Mousetrap Nipples'},
  {id: '703', name: 'Mr. Always Wants to be Hunted'},
  {id: '236', name: 'Mr. Beauregard'},
  {id: '237', name: 'Mr. Benson'},
  {id: '238', name: 'Mr. Booby Buyer'},
  {id: '614', name: 'Mr. Celery & Friends'},
  {id: '788', name: 'Mr. Cookie President'},
  {id: '239', name: 'Mr. Goldenfold'},
  {id: '240', name: 'Mr. Goldenfold'},
  {id: '241', name: 'Mr. Marklovitz'},
  {id: '242', name: 'Mr. Meeseeks'},
  {id: '243', name: 'Mr. Needful'},
  {id: '672', name: 'Mr. Nimbus'},
  {id: '684', name: 'Mr. Nimbus Secretary'},
  {id: '686', name: "Mr. Nimbus' Squid"},
  {id: '244', name: 'Mr. Poopybutthole'},
  {id: '409', name: 'Mr. Sneezy'},
  {id: '245', name: 'Mrs. Lipkip'},
  {id: '246', name: 'Mrs. Pancakes'},
  {id: '248', name: 'Mrs. Refrigerator'},
  {id: '249', name: 'Mrs. Sanchez'},
  {id: '250', name: 'Mrs. Sullivan'},
  {id: '418', name: "Mrs. Sullivan's Boyfriend"},
  {id: '416', name: 'Muscular Mannie'},
  {id: '615', name: 'Musical Fan'},
  {id: '251', name: 'Nancy'},
  {id: '456', name: 'Nano Doctor'},
  {id: '731', name: 'Naruto Smith'},
  {id: '765', name: 'Native Alien'},
  {id: '561', name: 'Netflix Executive'},
  {id: '670', name: 'New Improved Galactic Federation Guard'},
  {id: '671', name: 'New Improved Galactic Federation Guard'},
  {id: '789', name: 'Nick'},
  {id: '252', name: 'Noob-Noob'},
  {id: '253', name: 'Numbericon'},
  {id: '254', name: 'Octopus Man'},
  {id: '644', name: 'Old Glorzo'},
  {id: '413', name: 'Old Women'},
  {id: '255', name: 'Orthodox Jew'},
  {id: '489', name: 'P-Coat Rick'},
  {id: '795', name: 'Palicki'},
  {id: '816', name: 'Party Rick'},
  {id: '256', name: 'Pat Gueterman'},
  {id: '257', name: 'Paul Fleishman'},
  {id: '258', name: 'Pawnshop Clerk'},
  {id: '586', name: 'PC Basketball Player'},
  {id: '259', name: 'Pencilvester'},
  {id: '588', name: 'Pet Shop Employee'},
  {id: '616', name: 'Phantom of the Opera Fan'},
  {id: '260', name: 'Phillip Jacobs'},
  {id: '592', name: 'Phoenixperson'},
  {id: '617', name: 'Phoenixperson'},
  {id: '427', name: 'Phone-person'},
  {id: '428', name: 'Phone-person'},
  {id: '261', name: 'Photography Cyborg'},
  {id: '262', name: 'Photography Raptor'},
  {id: '263', name: 'Pibbles Bodyguard'},
  {id: '264', name: 'Pichael Thompson'},
  {id: '265', name: 'Pickle Rick'},
  {id: '266', name: 'Piece of Toast'},
  {id: '766', name: 'Pilgrim Alien'},
  {id: '444', name: 'Pink Polo Shirt Jerry'},
  {id: '424', name: 'Pizza-person'},
  {id: '425', name: 'Pizza-person'},
  {id: '653', name: 'Plane Crash Survivor'},
  {id: '654', name: 'Plane Crash Survivor'},
  {id: '717', name: 'Planetina'},
  {id: '724', name: 'Planetina Buyer'},
  {id: '267', name: 'Plumber Rick'},
  {id: '420', name: 'Plutonian Host'},
  {id: '419', name: 'Plutonian Hostess'},
  {id: '268', name: 'Poncho'},
  {id: '347', name: 'President Curtis'},
  {id: '767', name: 'President Turkey'},
  {id: '757', name: "President's General"},
  {id: '269', name: 'Presidentress of The Mega Gargantuans'},
  {id: '538', name: 'Priest Witherspoon'},
  {id: '270', name: 'Prince Nebulon'},
  {id: '730', name: 'Princess Ponietta'},
  {id: '271', name: 'Principal Vagina'},
  {id: '272', name: 'Principal Vagina'},
  {id: '435', name: 'Pripudlian'},
  {id: '479', name: 'Private Sector Rick'},
  {id: '618', name: 'Private Smith'},
  {id: '415', name: 'Pro trunk people marriage guy'},
  {id: '619', name: 'Professor Sanchez'},
  {id: '727', name: 'Professor Shabooboo'},
  {id: '514', name: 'Public Opinion Judge'},
  {id: '815', name: 'Punk Rick'},
  {id: '273', name: 'Purge Planet Ruler'},
  {id: '480', name: 'Purple Morty'},
  {id: '809', name: 'Pussifer'},
  {id: '274', name: 'Quantum Rick'},
  {id: '408', name: 'Quick Mystery Presenter'},
  {id: '620', name: 'Ramamama Lord'},
  {id: '555', name: 'Randotron'},
  {id: '275', name: 'Randy Dicknose'},
  {id: '276', name: 'Rat Boss'},
  {id: '811', name: 'Re-Build-a-Morty Morty'},
  {id: '277', name: 'Real Fake Doors Salesman'},
  {id: '820', name: 'Redhead Morty'},
  {id: '819', name: 'Redhead Rick'},
  {id: '663', name: 'Reggie'},
  {id: '278', name: 'Regional Manager Rick'},
  {id: '279', name: 'Regular Legs'},
  {id: '407', name: 'Regular Tyrion Lannister'},
  {id: '481', name: 'Retired General Rick'},
  {id: '280', name: 'Reverse Giraffe'},
  {id: '281', name: 'Reverse Rick Outrage'},
  {id: '282', name: 'Revolio Clockberg Jr.'},
  {id: '502', name: 'Revolio Clockberg Jr.'},
  {id: '771', name: 'Ricardo Montoya'},
  {id: '421', name: 'Rich Plutonian'},
  {id: '422', name: 'Rich Plutonian'},
  {id: '539', name: 'Richard'},
  {id: '286', name: 'Rick D-99'},
  {id: '283', name: 'Rick D. Sanchez III'},
  {id: '287', name: 'Rick D716'},
  {id: '288', name: 'Rick D716-B'},
  {id: '289', name: 'Rick D716-C'},
  {id: '284', name: 'Rick Guilt Rick'},
  {id: '291', name: 'Rick J-22'},
  {id: '292', name: 'Rick K-22'},
  {id: '285', name: 'Rick Prime'},
  {id: '1', name: 'Rick Sanchez'},
  {id: '290', name: 'Rick Sanchez'},
  {id: '293', name: 'Rick Sanchez'},
  {id: '631', name: 'Rick Sanchez'},
  {id: '781', name: "Rick's Garage"},
  {id: '638', name: 'Rick’s Disguise'},
  {id: '294', name: 'Ricktiminus Sancheziminius'},
  {id: '295', name: 'Riq IV'},
  {id: '296', name: 'Risotto Groupon'},
  {id: '297', name: "Risotto's Tentacled Henchman"},
  {id: '298', name: 'Robot Morty'},
  {id: '299', name: 'Robot Rick'},
  {id: '572', name: 'Robot Snake'},
  {id: '300', name: 'Roger'},
  {id: '301', name: 'Ron Benson'},
  {id: '393', name: 'Roy'},
  {id: '449', name: "Roy's Mum"},
  {id: '451', name: "Roy's Son"},
  {id: '450', name: "Roy's Wife"},
  {id: '302', name: 'Ruben'},
  {id: '540', name: 'Running Bird'},
  {id: '621', name: 'Ruth Bader Ginsburg'},
  {id: '794', name: 'Samansky'},
  {id: '303', name: 'Samantha'},
  {id: '622', name: 'Sarge'},
  {id: '796', name: 'Sarge'},
  {id: '817', name: 'Scar Rick'},
  {id: '691', name: 'Scarecrow Beth'},
  {id: '689', name: 'Scarecrow Jerry'},
  {id: '690', name: 'Scarecrow Morty'},
  {id: '687', name: 'Scarecrow Rick'},
  {id: '688', name: 'Scarecrow Summer'},
  {id: '304', name: 'Scary Brandon'},
  {id: '305', name: 'Scary Glenn'},
  {id: '396', name: 'Scary Teacher'},
  {id: '306', name: 'Scary Terry'},
  {id: '307', name: 'Scroopy Noopers'},
  {id: '308', name: 'Scropon'},
  {id: '309', name: 'Scrotian'},
  {id: '463', name: 'SEAL Team Rick'},
  {id: '464', name: 'SEAL Team Rick'},
  {id: '465', name: 'SEAL Team Rick'},
  {id: '466', name: 'SEAL Team Rick'},
  {id: '482', name: 'Secret Service Rick'},
  {id: '580', name: 'Secret Service Snake'},
  {id: '541', name: "Secretary at Tony's"},
  {id: '493', name: 'Secretary of the Interior'},
  {id: '310', name: 'Self-Congratulatory Jerry'},
  {id: '569', name: 'Shadow Jacker'},
  {id: '645', name: 'Shane'},
  {id: '442', name: 'Shaved Head Jerry'},
  {id: '484', name: 'Sheik Rick'},
  {id: '311', name: 'Shimshamian'},
  {id: '312', name: 'Shlaammi'},
  {id: '313', name: 'Shleemypants'},
  {id: '314', name: 'Shmlamantha Shmlicelli'},
  {id: '315', name: 'Shmlangela Shmlobinson-Shmlower'},
  {id: '316', name: 'Shmlona Shmlobinson'},
  {id: '317', name: 'Shmlonathan Shmlower'},
  {id: '318', name: 'Shmlony Shmlicelli'},
  {id: '319', name: 'Shmooglite Runner'},
  {id: '320', name: 'Shnoopy Bloopers'},
  {id: '623', name: 'Shrek The Musical Fan'},
  {id: '321', name: 'Shrimply Pibbles'},
  {id: '452', name: 'Simon'},
  {id: '322', name: 'Simple Rick'},
  {id: '797', name: 'Slartivartian'},
  {id: '323', name: 'Slaveowner'},
  {id: '324', name: 'Sleepy Gary'},
  {id: '325', name: 'Slick Morty'},
  {id: '326', name: 'Slippery Stair'},
  {id: '571', name: 'Slippy'},
  {id: '327', name: 'Slow Mobius'},
  {id: '328', name: 'Slow Rick'},
  {id: '568', name: 'Slut Dragon'},
  {id: '549', name: 'Snake Arms'},
  {id: '573', name: 'Snake Hitler'},
  {id: '574', name: 'Snake Lincoln'},
  {id: '576', name: 'Snake Linguist'},
  {id: '589', name: 'Snake Reporter'},
  {id: '575', name: 'Snake Resistance Robot'},
  {id: '578', name: 'Snake Soldier'},
  {id: '577', name: 'Snake Terminator'},
  {id: '579', name: 'Snake with Legs'},
  {id: '624', name: 'Snuffles'},
  {id: '329', name: 'Snuffles (Snowball)'},
  {id: '330', name: 'Solicitor Rick'},
  {id: '658', name: 'Sonia Sotomayor'},
  {id: '753', name: 'Space Cruiser'},
  {id: '736', name: 'Spaceman'},
  {id: '728', name: 'Sperm Queen'},
  {id: '406', name: 'Spiderweb teddy bear'},
  {id: '331', name: 'Squanchy'},
  {id: '666', name: 'Squeeb'},
  {id: '704', name: 'Squid Costume Beth'},
  {id: '705', name: 'Squid Costume Jerry'},
  {id: '706', name: 'Squid Costume Morty'},
  {id: '707', name: 'Squid Costume Rick'},
  {id: '708', name: 'Squid Costume Summer'},
  {id: '455', name: 'St. Gloopy Noops Nurse'},
  {id: '332', name: 'Stacy'},
  {id: '333', name: 'Stair Goblin'},
  {id: '810', name: 'Stan Lee Rick'},
  {id: '334', name: 'Stealy'},
  {id: '335', name: 'Steve'},
  {id: '646', name: 'Steve'},
  {id: '710', name: 'Steve'},
  {id: '483', name: 'Steve Jobs Rick'},
  {id: '336', name: 'Steven Phillips'},
  {id: '726', name: 'Sticky'},
  {id: '625', name: 'Storylord'},
  {id: '337', name: 'Stu'},
  {id: '3', name: 'Summer Smith'},
  {id: '338', name: 'Summer Smith'},
  {id: '339', name: 'Summer Smith'},
  {id: '629', name: 'Summer Smith'},
  {id: '800', name: 'Super Turkey'},
  {id: '434', name: 'Super Weird Rick'},
  {id: '340', name: 'Supernova'},
  {id: '652', name: 'SWAT Officer'},
  {id: '423', name: 'Synthetic Laser Eels'},
  {id: '341', name: 'Taddy Mason'},
  {id: '342', name: 'Taint Washer'},
  {id: '564', name: 'Talking Cat'},
  {id: '343', name: 'Tammy Guetermann'},
  {id: '344', name: 'Tammy Guetermann'},
  {id: '626', name: 'Tammy Guetermann'},
  {id: '486', name: 'Tan Rick'},
  {id: '443', name: 'Tank Top Jerry'},
  {id: '458', name: 'Tax Attorney'},
  {id: '345', name: 'Teacher Rick'},
  {id: '462', name: "Teleportation's Responsible Rick"},
  {id: '346', name: 'Terry'},
  {id: '627', name: 'The Concept of Time'},
  {id: '348', name: 'The President of the Miniverse'},
  {id: '349', name: 'The Scientist Formerly Known as Rick'},
  {id: '553', name: 'The Shapeshiftress'},
  {id: '563', name: 'The Wizard'},
  {id: '350', name: 'Thomas Lipkip'},
  {id: '351', name: 'Three Unknown Things'},
  {id: '593', name: 'Tickets Please Guy'},
  {id: '664', name: 'Ticktock'},
  {id: '352', name: 'Tinkles'},
  {id: '353', name: 'Tiny Rick'},
  {id: '399', name: 'Tiny-persons advocacy group lawyer'},
  {id: '354', name: 'Toby Matthews'},
  {id: '355', name: 'Todd Crystal'},
  {id: '356', name: 'Tom Randolph'},
  {id: '357', name: "Tommy's Clone"},
  {id: '531', name: 'Tony'},
  {id: '725', name: 'Tony Galopagus'},
  {id: '534', name: "Tony's Dad"},
  {id: '532', name: 'Tony’s Wife'},
  {id: '712', name: 'Too Cute to Murder Beth'},
  {id: '714', name: 'Too Cute to Murder Jerry'},
  {id: '715', name: 'Too Cute to Murder Morty'},
  {id: '713', name: 'Too Cute to Murder Rick'},
  {id: '716', name: 'Too Cute to Murder Summer'},
  {id: '358', name: 'Tophat Jones'},
  {id: '359', name: 'Tortured Morty'},
  {id: '360', name: 'Toxic Morty'},
  {id: '361', name: 'Toxic Rick'},
  {id: '362', name: 'Traflorkian'},
  {id: '460', name: 'Traflorkian Journalist'},
  {id: '632', name: 'Train Cop'},
  {id: '633', name: 'Train Cops'},
  {id: '634', name: 'Train Cops Instructor'},
  {id: '363', name: 'Trandor'},
  {id: '364', name: 'Tree Person'},
  {id: '365', name: 'Tricia Lange'},
  {id: '647', name: 'Troy'},
  {id: '548', name: 'Truckula'},
  {id: '367', name: 'Trunk Man'},
  {id: '366', name: 'Trunk Morty'},
  {id: '414', name: 'Trunkphobic guy'},
  {id: '405', name: 'Trunkphobic suspenders guy'},
  {id: '368', name: 'Truth Tortoise'},
  {id: '96', name: 'Tuberculosis'},
  {id: '371', name: 'Tumblorkian'},
  {id: '759', name: 'Turkey Morty'},
  {id: '761', name: 'Turkey President Curtis'},
  {id: '760', name: 'Turkey Rick'},
  {id: '369', name: 'Tusked Assassin'},
  {id: '410', name: 'Two Brothers'},
  {id: '787', name: 'Two Crows'},
  {id: '370', name: 'Two Guys with Handlebar Mustaches'},
  {id: '639', name: 'Uncle Nibbles'},
  {id: '391', name: 'Uncle Steve'},
  {id: '372', name: 'Unity'},
  {id: '380', name: 'Unknown Rick'},
  {id: '373', name: 'Unmuscular Michael'},
  {id: '374', name: 'Vampire Master'},
  {id: '453', name: "Vampire Master's Assistant"},
  {id: '375', name: 'Vance Maximus'},
  {id: '492', name: 'Varrix'},
  {id: '557', name: 'Ventriloquiver'},
  {id: '543', name: 'Vermigurber'},
  {id: '376', name: 'Veronica Ann Bennet'},
  {id: '439', name: 'Veterinary'},
  {id: '440', name: 'Veterinary Nurse'},
  {id: '487', name: 'Visor Rick'},
  {id: '774', name: 'Voiceoverian'},
  {id: '775', name: 'Voiceoverian'},
  {id: '377', name: 'Voltematron'},
  {id: '378', name: 'Wall Crawling Rick'},
  {id: '682', name: 'Warlock'},
  {id: '521', name: 'Wasp Beth'},
  {id: '520', name: 'Wasp Jerry'},
  {id: '518', name: 'Wasp Morty'},
  {id: '516', name: 'Wasp Rick'},
  {id: '517', name: 'Wasp Rick’s Clone'},
  {id: '519', name: 'Wasp Summer'},
  {id: '723', name: 'Water Tina-Teer'},
  {id: '379', name: 'Wedding Bartender'},
  {id: '711', name: 'When Wolf'},
  {id: '697', name: 'Wicker Beth'},
  {id: '699', name: 'Wicker Morty'},
  {id: '698', name: 'Wicker Rick'},
  {id: '700', name: 'Wicker Summer'},
  {id: '381', name: 'Woman Rick'},
  {id: '382', name: 'Worldender'},
  {id: '772', name: 'Wrap-it-up Little Rick'},
  {id: '721', name: 'Xing Ho'},
  {id: '383', name: 'Yaarb'},
  {id: '384', name: 'Yellow Headed Doctor'},
  {id: '385', name: 'Yellow Shirt Rick'},
  {id: '773', name: 'Yo-yo Rick'},
  {id: '823', name: 'Young Beth'},
  {id: '824', name: 'Young Beth'},
  {id: '822', name: 'Young Jerry'},
  {id: '825', name: 'Young Jerry'},
  {id: '779', name: 'Young Memory Rick'},
  {id: '386', name: 'Zarbadar Gloonch'},
  {id: '387', name: "Zarbadar's Mytholog"},
  {id: '388', name: 'Zeep Xanflorp'},
  {id: '389', name: 'Zeta Alpha Rick'},
  {id: '390', name: 'Zick Zack'},
];
